"use client"

/**
 * AI lecture brief.
 *
 * Runs only after a lecture, never during detection — the realtime path must
 * not compete with a 45 second summarisation call. The `source` field is shown
 * verbatim so the user knows whether Qwen produced the brief or the local
 * extractive fallback did.
 */

import { useMemo, useState } from "react"
import { BrainCircuit, Sparkles } from "lucide-react"
import { useHader } from "@/components/providers/hader-provider"
import { saveBrief } from "@/lib/history"
import { Button, Card, Kicker } from "@/components/ui/status"
import type { LectureBrief } from "@/lib/types"

export default function NotesPage() {
  const { session, lecture } = useHader()
  const [brief, setBrief] = useState<LectureBrief | null>(null)
  const [pasted, setPasted] = useState("")
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const liveTranscript = useMemo(
    () =>
      session.segments
        .filter((segment) => segment.isFinal)
        .map((segment) => segment.text)
        .join(" ")
        .trim(),
    [session.segments],
  )

  const transcript = pasted.trim() || liveTranscript
  const wordCount = transcript ? transcript.split(/\s+/).length : 0
  const tooShort = wordCount < 30

  async function generate() {
    setLoading(true)
    setError(null)
    try {
      const res = await fetch("/api/ai/brief", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          transcript,
          course: lecture.course,
          language: lecture.language === "both" ? "en" : lecture.language,
        }),
      })
      const data = await res.json()
      if (!res.ok) {
        setError(data?.error?.message ?? "The brief could not be generated.")
        return
      }
      setBrief(data as LectureBrief)
      if (session.sessionId) saveBrief(session.sessionId, data as LectureBrief)
    } catch {
      setError("Network error — the summariser could not be reached.")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex flex-col gap-4">
      <header>
        <Kicker>AI notes</Kicker>
        <h1 className="mt-1 text-2xl font-bold tracking-tight">Lecture brief</h1>
        <p className="mt-1 text-pretty text-xs leading-relaxed text-muted-foreground">
          Turns a transcript into a summary, definitions, exam points and a short quiz. It only uses
          what was actually said — nothing is invented to fill a section.
        </p>
      </header>

      <Card>
        <div className="flex flex-wrap items-center gap-3">
          <div className="flex-1">
            <Kicker>Source transcript</Kicker>
            <p className="mt-1 text-[11px] text-muted-foreground">
              {liveTranscript
                ? `${liveTranscript.split(/\s+/).length} words captured from the current session.`
                : "No live transcript in memory — paste one below."}
            </p>
          </div>
          <Button variant="primary" onClick={generate} disabled={loading || tooShort}>
            <Sparkles className="size-3.5" aria-hidden />
            {loading ? "Generating…" : "Generate brief"}
          </Button>
        </div>

        <label className="mt-3 block">
          <span className="sr-only">Paste a transcript</span>
          <textarea
            value={pasted}
            onChange={(event) => setPasted(event.target.value)}
            dir="auto"
            rows={6}
            placeholder="Paste a lecture transcript here to override the live one…"
            className="w-full resize-y rounded-lg border border-border bg-secondary/40 p-3 text-xs leading-relaxed outline-none focus-visible:ring-2 focus-visible:ring-[var(--ring)]"
          />
        </label>
        <p className="mt-1 text-[11px] text-muted-foreground">
          {wordCount} words{tooShort ? " · at least 30 words are needed for a useful brief" : ""}
        </p>
      </Card>

      {error && (
        <Card className="border-destructive/40 bg-destructive/5">
          <p className="text-xs font-bold text-destructive">Could not generate</p>
          <p className="mt-1 text-[11px] text-muted-foreground">{error}</p>
        </Card>
      )}

      {brief && (
        <div className="flex flex-col gap-4">
          <Card className={brief.source === "local" ? "border-warn/40 bg-warn/5" : "border-good/40 bg-good/5"}>
            <p className="flex items-center gap-2 text-xs font-bold">
              <BrainCircuit className="size-4" aria-hidden />
              {brief.source === "qwen" ? "Generated by Qwen" : "Local extractive fallback"}
            </p>
            <p className="mt-1 text-pretty text-[11px] leading-relaxed text-muted-foreground">
              {brief.source === "qwen"
                ? "Produced by the configured Qwen text model from your transcript."
                : "Qwen was unavailable, so this brief was extracted on-device by ranking sentences. It is thinner than a model-generated brief — that is expected, not a failure."}
            </p>
          </Card>

          <Card>
            <Kicker>Summary</Kicker>
            <p dir="auto" className="mt-2 text-pretty text-xs leading-relaxed">
              {brief.summary || "No summary could be extracted."}
            </p>
          </Card>

          <div className="grid gap-4 lg:grid-cols-2">
            <ListCard title="Key concepts" items={brief.keyConcepts} />
            <ListCard title="Exam points" items={brief.examPoints} />
            <ListCard title="Assignments" items={brief.assignments} />
            <ListCard title="Review these" items={brief.questionsToReview} />
          </div>

          {brief.definitions.length > 0 && (
            <Card>
              <Kicker>Definitions</Kicker>
              <dl className="mt-2 flex flex-col divide-y divide-border">
                {brief.definitions.map((item) => (
                  <div key={item.term} className="py-2">
                    <dt dir="auto" className="text-xs font-bold">
                      {item.term}
                    </dt>
                    <dd dir="auto" className="text-pretty text-[11px] leading-relaxed text-muted-foreground">
                      {item.meaning}
                    </dd>
                  </div>
                ))}
              </dl>
            </Card>
          )}

          {brief.quiz.length > 0 && (
            <Card>
              <Kicker>Self-check quiz</Kicker>
              <ol className="mt-2 flex flex-col gap-2">
                {brief.quiz.map((item, index) => (
                  <li key={index}>
                    <details className="rounded-lg border border-border px-3 py-2">
                      <summary dir="auto" className="cursor-pointer text-xs font-semibold">
                        {item.question}
                      </summary>
                      <p dir="auto" className="mt-2 text-pretty text-[11px] leading-relaxed text-muted-foreground">
                        {item.answer}
                      </p>
                    </details>
                  </li>
                ))}
              </ol>
            </Card>
          )}
        </div>
      )}
    </div>
  )
}

function ListCard({ title, items }: { title: string; items: string[] }) {
  return (
    <Card>
      <Kicker>{title}</Kicker>
      {items.length === 0 ? (
        <p className="mt-2 text-[11px] text-muted-foreground">Nothing in the transcript supported this.</p>
      ) : (
        <ul className="mt-2 flex flex-col gap-1.5">
          {items.map((item) => (
            <li key={item} dir="auto" className="text-pretty text-[11px] leading-relaxed">
              {item}
            </li>
          ))}
        </ul>
      )}
    </Card>
  )
}
